package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTACHMENT".
 */
public class Attachment {

    private Long id;
    private String attachmentId;
    private String type;
    private String name;
    private Double size;
    private String URL;
    private String additionalInfo;
    private java.util.Date timeStamp;
    private Integer syncStatus;

    public Attachment() {
    }

    public Attachment(Long id) {
        this.id = id;
    }

    public Attachment(Long id, String attachmentId, String type, String name, Double size, String URL, String additionalInfo, java.util.Date timeStamp, Integer syncStatus) {
        this.id = id;
        this.attachmentId = attachmentId;
        this.type = type;
        this.name = name;
        this.size = size;
        this.URL = URL;
        this.additionalInfo = additionalInfo;
        this.timeStamp = timeStamp;
        this.syncStatus = syncStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getSize() {
        return size;
    }

    public void setSize(Double size) {
        this.size = size;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }

    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public java.util.Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(java.util.Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Integer getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(Integer syncStatus) {
        this.syncStatus = syncStatus;
    }

}
