package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_USER".
 */
public class ChatUser {

    private Long id;
    private Integer userId;
    private String name;
    private String number;
    private String email;
    private java.util.Date lastRequestAt;
    private String role;
    private java.util.Date timeStamp;
    private Integer syncStatus;

    public ChatUser() {
    }

    public ChatUser(Long id) {
        this.id = id;
    }

    public ChatUser(Long id, Integer userId, String name, String number, String email, java.util.Date lastRequestAt, String role, java.util.Date timeStamp, Integer syncStatus) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.number = number;
        this.email = email;
        this.lastRequestAt = lastRequestAt;
        this.role = role;
        this.timeStamp = timeStamp;
        this.syncStatus = syncStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public java.util.Date getLastRequestAt() {
        return lastRequestAt;
    }

    public void setLastRequestAt(java.util.Date lastRequestAt) {
        this.lastRequestAt = lastRequestAt;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public java.util.Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(java.util.Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Integer getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(Integer syncStatus) {
        this.syncStatus = syncStatus;
    }

}
