package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIALOG_NOTIFICATION".
 */
public class DialogNotification {

    private Long id;
    private String notificationId;
    private String dialogId;
    private String state;
    private String body;
    private Long createdDate;
    private String type;

    public DialogNotification() {
    }

    public DialogNotification(Long id) {
        this.id = id;
    }

    public DialogNotification(Long id, String notificationId, String dialogId, String state, String body, Long createdDate, String type) {
        this.id = id;
        this.notificationId = notificationId;
        this.dialogId = dialogId;
        this.state = state;
        this.body = body;
        this.createdDate = createdDate;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNotificationId() {
        return notificationId;
    }

    public void setNotificationId(String notificationId) {
        this.notificationId = notificationId;
    }

    public String getDialogId() {
        return dialogId;
    }

    public void setDialogId(String dialogId) {
        this.dialogId = dialogId;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Long createdDate) {
        this.createdDate = createdDate;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
