package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIALOG".
 */
public class Dialog {

    private Long id;
    private String dialogId;
    private String name;
    private String lastMessage;
    private Long lastMessageDateSent;
    private Integer lastMessageUserId;
    private Integer userId;
    private String xmppRoomJid;
    private Integer unreadMessagesCount;
    private String imageUrl;
    private String type;
    private Integer status;
    private java.util.Date timeStamp;

    public Dialog() {
    }

    public Dialog(Long id) {
        this.id = id;
    }

    public Dialog(Long id, String dialogId, String name, String lastMessage, Long lastMessageDateSent, Integer lastMessageUserId, Integer userId, String xmppRoomJid, Integer unreadMessagesCount, String imageUrl, String type, Integer status, java.util.Date timeStamp) {
        this.id = id;
        this.dialogId = dialogId;
        this.name = name;
        this.lastMessage = lastMessage;
        this.lastMessageDateSent = lastMessageDateSent;
        this.lastMessageUserId = lastMessageUserId;
        this.userId = userId;
        this.xmppRoomJid = xmppRoomJid;
        this.unreadMessagesCount = unreadMessagesCount;
        this.imageUrl = imageUrl;
        this.type = type;
        this.status = status;
        this.timeStamp = timeStamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDialogId() {
        return dialogId;
    }

    public void setDialogId(String dialogId) {
        this.dialogId = dialogId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public Long getLastMessageDateSent() {
        return lastMessageDateSent;
    }

    public void setLastMessageDateSent(Long lastMessageDateSent) {
        this.lastMessageDateSent = lastMessageDateSent;
    }

    public Integer getLastMessageUserId() {
        return lastMessageUserId;
    }

    public void setLastMessageUserId(Integer lastMessageUserId) {
        this.lastMessageUserId = lastMessageUserId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getXmppRoomJid() {
        return xmppRoomJid;
    }

    public void setXmppRoomJid(String xmppRoomJid) {
        this.xmppRoomJid = xmppRoomJid;
    }

    public Integer getUnreadMessagesCount() {
        return unreadMessagesCount;
    }

    public void setUnreadMessagesCount(Integer unreadMessagesCount) {
        this.unreadMessagesCount = unreadMessagesCount;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public java.util.Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(java.util.Date timeStamp) {
        this.timeStamp = timeStamp;
    }

}
