package com.trutek.looped.data.impl.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.trutek.looped.data.impl.entities.DialogUsers;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIALOG_USERS".
*/
public class DialogUsersDao extends AbstractDao<DialogUsers, Long> {

    public static final String TABLENAME = "DIALOG_USERS";

    /**
     * Properties of entity DialogUsers.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserStatus = new Property(1, String.class, "userStatus", false, "USER_STATUS");
        public final static Property DialogId = new Property(2, String.class, "dialogId", false, "DIALOG_ID");
        public final static Property UserId = new Property(3, int.class, "userId", false, "USER_ID");
    };


    public DialogUsersDao(DaoConfig config) {
        super(config);
    }
    
    public DialogUsersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIALOG_USERS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_STATUS\" TEXT NOT NULL ," + // 1: userStatus
                "\"DIALOG_ID\" TEXT NOT NULL ," + // 2: dialogId
                "\"USER_ID\" INTEGER NOT NULL );"); // 3: userId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_DIALOG_USERS_DIALOG_ID_USER_ID ON DIALOG_USERS" +
                " (\"DIALOG_ID\",\"USER_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIALOG_USERS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DialogUsers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserStatus());
        stmt.bindString(3, entity.getDialogId());
        stmt.bindLong(4, entity.getUserId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DialogUsers readEntity(Cursor cursor, int offset) {
        DialogUsers entity = new DialogUsers( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // userStatus
            cursor.getString(offset + 2), // dialogId
            cursor.getInt(offset + 3) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DialogUsers entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserStatus(cursor.getString(offset + 1));
        entity.setDialogId(cursor.getString(offset + 2));
        entity.setUserId(cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DialogUsers entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DialogUsers entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
