package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HEALTH_PARAM_LOG".
 */
public class HealthParamLog {

    private Long id;
    private String serverId;
    private Integer value;
    private String unit;
    private java.util.Date createdAt;
    private Long healthChartId;

    public HealthParamLog() {
    }

    public HealthParamLog(Long id) {
        this.id = id;
    }

    public HealthParamLog(Long id, String serverId, Integer value, String unit, java.util.Date createdAt, Long healthChartId) {
        this.id = id;
        this.serverId = serverId;
        this.value = value;
        this.unit = unit;
        this.createdAt = createdAt;
        this.healthChartId = healthChartId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public Long getHealthChartId() {
        return healthChartId;
    }

    public void setHealthChartId(Long healthChartId) {
        this.healthChartId = healthChartId;
    }

}
