package com.trutek.looped.data.impl.entities;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.trutek.looped.data.impl.entities.Interest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INTEREST".
*/
public class InterestDao extends AbstractDao<Interest, Long> {

    public static final String TABLENAME = "INTEREST";

    /**
     * Properties of entity Interest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property ServerId = new Property(2, String.class, "serverId", false, "SERVER_ID");
        public final static Property CommunityId = new Property(3, String.class, "communityId", false, "COMMUNITY_ID");
        public final static Property TimeStamp = new Property(4, java.util.Date.class, "timeStamp", false, "TIME_STAMP");
        public final static Property SyncStatus = new Property(5, String.class, "syncStatus", false, "SYNC_STATUS");
        public final static Property ProfileId = new Property(6, Long.class, "profileId", false, "PROFILE_ID");
    };

    private DaoSession daoSession;

    private Query<Interest> profile_InterestListQuery;

    public InterestDao(DaoConfig config) {
        super(config);
    }
    
    public InterestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INTEREST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"SERVER_ID\" TEXT," + // 2: serverId
                "\"COMMUNITY_ID\" TEXT," + // 3: communityId
                "\"TIME_STAMP\" INTEGER," + // 4: timeStamp
                "\"SYNC_STATUS\" TEXT," + // 5: syncStatus
                "\"PROFILE_ID\" INTEGER);"); // 6: profileId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INTEREST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Interest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(3, serverId);
        }
 
        String communityId = entity.getCommunityId();
        if (communityId != null) {
            stmt.bindString(4, communityId);
        }
 
        java.util.Date timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(5, timeStamp.getTime());
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(6, syncStatus);
        }
 
        Long profileId = entity.getProfileId();
        if (profileId != null) {
            stmt.bindLong(7, profileId);
        }
    }

    @Override
    protected void attachEntity(Interest entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Interest readEntity(Cursor cursor, int offset) {
        Interest entity = new Interest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // serverId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // communityId
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // timeStamp
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // syncStatus
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // profileId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Interest entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setServerId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCommunityId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTimeStamp(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setSyncStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setProfileId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Interest entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Interest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "interestList" to-many relationship of Profile. */
    public List<Interest> _queryProfile_InterestList(Long profileId) {
        synchronized (this) {
            if (profile_InterestListQuery == null) {
                QueryBuilder<Interest> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProfileId.eq(null));
                profile_InterestListQuery = queryBuilder.build();
            }
        }
        Query<Interest> query = profile_InterestListQuery.forCurrentThread();
        query.setParameter(0, profileId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getProfileDao().getAllColumns());
            builder.append(" FROM INTEREST T");
            builder.append(" LEFT JOIN PROFILE T0 ON T.\"PROFILE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Interest loadCurrentDeep(Cursor cursor, boolean lock) {
        Interest entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Profile profile = loadCurrentOther(daoSession.getProfileDao(), cursor, offset);
        entity.setProfile(profile);

        return entity;    
    }

    public Interest loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Interest> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Interest> list = new ArrayList<Interest>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Interest> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Interest> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
