package com.trutek.looped.data.impl.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.trutek.looped.data.impl.entities.Loop;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOOP".
*/
public class LoopDao extends AbstractDao<Loop, Long> {

    public static final String TABLENAME = "LOOP";

    /**
     * Properties of entity Loop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Status = new Property(2, String.class, "status", false, "STATUS");
        public final static Property Role = new Property(3, String.class, "role", false, "ROLE");
        public final static Property ProfileId = new Property(4, String.class, "profileId", false, "PROFILE_ID");
        public final static Property PicUrl = new Property(5, String.class, "picUrl", false, "PIC_URL");
        public final static Property ServerId = new Property(6, String.class, "serverId", false, "SERVER_ID");
        public final static Property RecipientId = new Property(7, String.class, "recipientId", false, "RECIPIENT_ID");
        public final static Property TimeStamp = new Property(8, java.util.Date.class, "timeStamp", false, "TIME_STAMP");
        public final static Property SyncStatus = new Property(9, String.class, "syncStatus", false, "SYNC_STATUS");
    };


    public LoopDao(DaoConfig config) {
        super(config);
    }
    
    public LoopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOOP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"STATUS\" TEXT," + // 2: status
                "\"ROLE\" TEXT," + // 3: role
                "\"PROFILE_ID\" TEXT," + // 4: profileId
                "\"PIC_URL\" TEXT," + // 5: picUrl
                "\"SERVER_ID\" TEXT NOT NULL ," + // 6: serverId
                "\"RECIPIENT_ID\" TEXT NOT NULL ," + // 7: recipientId
                "\"TIME_STAMP\" INTEGER," + // 8: timeStamp
                "\"SYNC_STATUS\" TEXT);"); // 9: syncStatus
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_LOOP_SERVER_ID_RECIPIENT_ID ON LOOP" +
                " (\"SERVER_ID\",\"RECIPIENT_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOOP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Loop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(3, status);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(4, role);
        }
 
        String profileId = entity.getProfileId();
        if (profileId != null) {
            stmt.bindString(5, profileId);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(6, picUrl);
        }
        stmt.bindString(7, entity.getServerId());
        stmt.bindString(8, entity.getRecipientId());
 
        java.util.Date timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(9, timeStamp.getTime());
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(10, syncStatus);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Loop readEntity(Cursor cursor, int offset) {
        Loop entity = new Loop( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // status
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // role
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // profileId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // picUrl
            cursor.getString(offset + 6), // serverId
            cursor.getString(offset + 7), // recipientId
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // timeStamp
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // syncStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Loop entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRole(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setProfileId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPicUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setServerId(cursor.getString(offset + 6));
        entity.setRecipientId(cursor.getString(offset + 7));
        entity.setTimeStamp(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setSyncStatus(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Loop entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Loop entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
