package com.trutek.looped.data.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private String messageId;
    private String dialogId;
    private String body;
    private Long dateSent;
    private Integer recipientId;
    private Integer senderId;
    private String state;
    private String status;
    private java.util.Date timeStamp;
    private String attachmentId;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String messageId, String dialogId, String body, Long dateSent, Integer recipientId, Integer senderId, String state, String status, java.util.Date timeStamp, String attachmentId) {
        this.id = id;
        this.messageId = messageId;
        this.dialogId = dialogId;
        this.body = body;
        this.dateSent = dateSent;
        this.recipientId = recipientId;
        this.senderId = senderId;
        this.state = state;
        this.status = status;
        this.timeStamp = timeStamp;
        this.attachmentId = attachmentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getDialogId() {
        return dialogId;
    }

    public void setDialogId(String dialogId) {
        this.dialogId = dialogId;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Long getDateSent() {
        return dateSent;
    }

    public void setDateSent(Long dateSent) {
        this.dateSent = dateSent;
    }

    public Integer getRecipientId() {
        return recipientId;
    }

    public void setRecipientId(Integer recipientId) {
        this.recipientId = recipientId;
    }

    public Integer getSenderId() {
        return senderId;
    }

    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(java.util.Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

}
